# steemitapi default configuration, override in your config/local.toml

# port to listen on
port = 8090

# application name used for logging and service namespace
name = 'steemitapi'

# number of worker processes to spawn, 0 = autodetect
num_workers = 1

# logging output, can be repeated
[[log]]
level = 'debug'
out = 'stdout' # path or stdout/err

# storage for drafts
[storage]
type = 'memory' # valid types are: memory, s3
# s3_access_key = 'foo'
# s3_secret_key = 'bar'
# s3_bucket = 'mybucket'
