num_workers = 0
port = 8080
rpc_node = 'https://api.steemit.com'
admin_role = 'steem'
[storage]
type = 's3'
[[log]]
level = 'info'
out = 'stdout'
[database]
dialect = 'postgres'
[database.dialectOptions]
ssl = true
[cacheClient]
ttl = 600
interval = 60